elastic-rs/elastic

Cargo.toml, examples/typed.rs, src/errors.rs, src/lib.rs, tests/mod.rs
Part of #153 
This aims to add some traits that make it easy to build request types in `elastic_requests` from document types in `elastic_types`. It's a first pass so is a bit raw.
I'm not convinced the definitions so far are any good. Mostly because the trait methods are trying to cover the whole parameter surface when they shouldn't. It'd be better to take a `self` argument so builders can be supported in the future.
That way they don't need to cover everything, and additional parameters can be provided by tuples (this is ok because we've got type wrappers for each one, `(Type::from("ty"), Id::from("1"))` is not the same as `(Id::from("1"), Type::from("ty"))`. We could also offer bespoke builders that can be used to construct requests.
=> Glue Traits between Types and Requests

Cargo.toml, README.md, examples/basic.rs, examples/typed.rs, src/http_client.rs, src/impls.rs, src/lib.rs, tests/mod.rs
This PR stops re-exporting bits of `elastic_reqwest` and wraps them up in a common `Client` API. The samples have been updated appropriately.
Once this is sorted the current API surface should be cleaned up with some proper tests and refactored into separate modules for better maintainability.
=> Add a Http Client wrapper

src/client.rs, src/error.rs, src/impls.rs, src/lib.rs
Closes #172 
Working through some documentation for the `elastic` crate. The only bit I don't really like is duplicating docs between `elastic` and `elastic_types`. Feels a bit dirty...
The goal though is to get some decent documentation that describes how to use the library and how to get started customising for specific use cases.
=> [WIP] Documentation

benches/rust/elastic-raw/Cargo.toml, benches/rust/elastic-raw/src/main.rs, benches/rust/elastic/Cargo.toml, benches/rust/elastic/src/main.rs, elastic/Cargo.toml, elastic/examples/account_sample/Cargo.toml, elastic/examples/account_sample/src/ops/commands/ensure_bank_index_exists.rs, elastic/examples/account_sample/src/ops/commands/put_bulk_accounts.rs, elastic/examples/account_sample/src/ops/queries/simple_search.rs, elastic/examples/typed.rs, elastic/src/client.rs, elastic/src/impls.rs, elastic/tests/mod.rs
Part of #178 
This is a breaking change that makes the body buffer a generic type instead of `Cow<'a, [u8]>`, and removes the ability to convert a borrowed request into a `HttpRequest` (you can still used borrowed bodies though). This means the underlying http transport can decide what kinds of body types it will accept, rather than the request types forcing that decision.
`elastic` now accepts any type that is `Into<reqwest::Body>`, so it supports the previous types plus `File`. With stable specialisation we could add some more concrete types.
I haven't gone through the benchmarks yet (it should be much of a muchness), but will check those out and let the API simmer for a bit before merging. On the stable channel, the request body will be copied by `reqwest` if you use borrowed data, …
=> Update to generic requests

elastic/examples/typed.rs
Just removing an unneeded `serde_json` import from the `typed` sample.
=> Remove unneeded use

elastic/src/client/mod.rs, elastic/src/client/requests/mod.rs, elastic/src/client/responses/mod.rs, elastic/src/lib.rs
Just reworks the `ResponseBuilder` so it's more obvious what `IntoResponseBuilder` and `HttpResponse` are for. This doesn't affect the public API.
=> Tweak Response internals

.travis.yml, elastic/examples/async_sample/Cargo.toml, elastic/examples/async_sample/README.md, elastic/examples/async_sample/src/body.rs, elastic/examples/async_sample/src/error.rs, elastic/examples/async_sample/src/main.rs
Reworks the async sample a bit to avoid copying the response when deserialising. Also uses `string-cache` for interning the `index` and `type` fields in the bulk response.
Avoiding the response copy is actually slower than just buffering into a `Vec<u8>`, but is much more memory efficient.
=> Refactor async sample

elastic/examples/async_sample/src/body/mod.rs, elastic/examples/async_sample/src/body/request.rs, elastic/examples/async_sample/src/body/response.rs, elastic/examples/async_sample/src/error.rs, elastic/examples/async_sample/src/main.rs
Splits the `body` module into `request` and `response`. Nothing much to see here.
=> More async sample

elastic/examples/custom_response.rs, elastic/src/client/responses/parse.rs
Adds a sample for `IsOk` and re-exports the parse error in the module that actually used it.
=> add a sample for IsOk

elastic/examples/account_sample/src/ops/commands/put_bulk_accounts.rs, elastic/examples/custom_response.rs, elastic/src/client/mod.rs, elastic/src/client/requests/create_index.rs, elastic/src/client/requests/get_document.rs, elastic/src/client/requests/index_document.rs, elastic/src/client/requests/mod.rs, elastic/src/client/requests/put_mapping.rs, elastic/src/client/requests/search.rs, elastic/src/client/responses/mod.rs
- Removes the additional `TBody` generic from `RequestBuilder`, so it only takes a type for the inner request.
- Use `?` instead of `and_then` in a few places
I'm trying to make the request and response types consistent so they could potentially be used as inputs to some `tokio_service::Service` in an async API.
=> Make request builder consistent

derive/Cargo.toml, elastic/Cargo.toml, elastic/examples/async_sample/Cargo.toml, elastic/examples/async_sample/src/body/response.rs, elastic/src/client/responses/mod.rs
- Updates to the stable `string-cache` with `serde 1.0` support
- Removes the deprecated `ResponseBuilder::raw` method
- Update versions to `0.13.0` on `master`
=> Update to stable string-cache

derive/Cargo.toml, elastic/Cargo.toml
Fixes an issue with the yanked `0.3.1` version of `chrono`
=> Update to elastic_types 0.18.0

benches/rust/Cargo.toml, benches/rust/README.md, benches/rust/elastic/Cargo.toml, benches/rust/elastic/src/main.rs, benches/rust/elastic_bulk/Cargo.toml, benches/rust/elastic_bulk/src/main.rs, benches/rust/elastic_raw/src/main.rs, benches/rust/measure/.gitignore, benches/rust/measure/Cargo.toml, benches/rust/measure/src/lib.rs, benches/rust/prepare/.gitignore, benches/rust/prepare/Cargo.toml, benches/rust/prepare/src/main.rs, benches/rust/rs-es/Cargo.toml, benches/rust/rs-es/src/main.rs
Makes it easier to add new benches and see what they're doing by extracting the bench running and reporting into a common crate. At some point we should look into proper benchmarking for the client, using a proper benchmarking framework instead of this home-grown one.
=> Extract common bench code

benches/rust/elastic_bulk/Cargo.toml, benches/rust/elastic_bulk/src/main.rs
This just adds a few more switches to the bulk benchmark so the impact of various configurations can be measured.
=> Add more switches to bulk bench

elastic/Cargo.toml, elastic/examples/account_sample/src/ops/commands/ensure_bank_index_exists.rs, elastic/examples/account_sample/src/ops/commands/put_bulk_accounts.rs, elastic/examples/basic.rs, elastic/examples/bulk.rs, elastic/examples/custom_response.rs, elastic/examples/get.rs, elastic/examples/index.rs, elastic/examples/ping.rs, elastic/examples/raw.rs, elastic/examples/typed.rs, elastic/src/client/requests/mod.rs, elastic/src/lib.rs
Closes #219 
Adds some really basic logging to requests and hooks up `env_logger` in each example. Set:
```
export RUST_LOG=debug
```
To see logs for Elasticsearch requests.
=> Add basic request logging

elastic/src/error.rs
Fixes an issue with some unused doc comments in the `error_chain` macro that are reported as a warning on the latest `nightly`.
=> Fix build on nightly

benches/elastic/Cargo.toml, benches/elastic_bulk/Cargo.toml, benches/elastic_bulk/src/main.rs, benches/elastic_raw/Cargo.toml, benches/measure/Cargo.toml, benches/prepare/Cargo.toml, benches/rs-es/Cargo.toml, ci/nightly.sh, ci/stable.sh, ci/travis.sh, examples/account_sample/Cargo.toml, examples/async_raw_sample/Cargo.toml, src/elastic/src/client/async.rs, src/elastic/src/client/sync.rs, src/reqwest/benches/mod.rs, src/reqwest/src/async.rs, src/reqwest/src/sync.rs, src/types/tests/derive_compile_test/Cargo.toml, tests/run/Cargo.toml
We're tracking the `master` branch of `reqwest`, which now requires using a builder to handle errors instead of panicking.
=> Track latest reqwest release

README.md, benches/elastic_async/Cargo.toml, benches/elastic_async/src/main.rs, examples/account_sample/src/ops/commands/ensure_bank_index_exists.rs, examples/account_sample/src/ops/commands/put_bulk_accounts.rs, src/elastic/examples/typed_async.rs, src/elastic/src/client/async.rs, src/elastic/src/client/mod.rs, src/elastic/src/client/requests/document_get.rs, src/elastic/src/client/requests/document_index.rs, src/elastic/src/client/requests/document_put_mapping.rs, src/elastic/src/client/requests/index_create.rs, src/elastic/src/client/requests/mod.rs, src/elastic/src/client/requests/raw.rs, src/elastic/src/client/requests/search.rs, src/elastic/src/client/responses/async.rs, src/elastic/src/client/responses/mod.rs, src/elastic/src/client/responses/parse.rs, src/elastic/src/error.rs, src/elastic/src/lib.rs, src/reqwest/src/async.rs, src/reqwest/src/lib.rs, src/reqwest/src/sync.rs, tests/run/src/build_client.rs, tests/run/src/run_tests.rs, tests/run/src/search/no_index.rs, tests/run/src/wait_until_ready.rs
Part of #231.
- add explicit preludes so we can control exported types better
- add concrete futures in place of Boxes
- tidy up some links and readme
=> Cleanup futures and preludes

README.md, ci/nightly.sh, examples/async_raw_sample/src/body/request.rs, examples/async_raw_sample/src/main.rs
Upload crate docs on the `master` branch. This should be more helpful for times when `master` diverges significantly from what's on `crates.io`, as it is now.
=> Upload docs on build

examples/account_sample/src/model/index.rs, src/elastic/src/client/async.rs, src/elastic/src/client/sync.rs
Closes #239 
Adds a trait that can be used to construct an underlying `reqwest` client in the async builder. This avoids the ambiguity of supplying a `reqwest` client and then having to also supply a redundant `Handle` when building.
=> Accept HttpClient or Handle when building async client

README.md, ci/nightly.sh
I've added a `vNext` branch we can merge breaking changes into and keep around for the next breaking release. Docs are built off this branch, since it's likely to be in a different state to `master`, which should always be available on crates.io as the latest version.
=> Build docs for vNext branch and add gitter chat

README.md, src/elastic/Cargo.toml, src/elastic/README.md, src/elastic_derive/Cargo.toml, src/requests/Cargo.toml, src/reqwest/Cargo.toml, src/responses/Cargo.toml, src/types/Cargo.toml, src/types_derive/Cargo.toml, src/types_derive_internals/Cargo.toml
Include `README.md` files in `Cargo.toml`s so they'll be rendered on `crates.io`.
=> Include readmes in cargo tomls

src/responses/Cargo.toml, src/responses/src/lib.rs, src/responses/src/search.rs
It doesn't really need to be there anymore and means we don't need a dependency on `slog`, which was breaking the build in `nightly`.
=> Remove explicit logging from responses

src/reqwest/Cargo.toml, src/responses/Cargo.toml
Part of #283 
The bound on `quick-error` and `bytes` are tighter than they need to be.
=> Loosen version bound on quick-error

src/elastic/examples/index.rs, src/elastic/src/client/async.rs, src/elastic/src/client/requests/index_exists.rs, src/elastic/src/client/requests/mod.rs, src/elastic/src/client/responses/mod.rs, src/elastic/src/client/sync.rs, src/responses/src/indices_exists.rs, src/responses/src/lib.rs, src/responses/src/parsing.rs, src/responses/tests/indices_exists/mod.rs, src/responses/tests/mod.rs
Part of #256 
- Adds an `index_exists` method to the client
- Adds support for specifying a new response body as json when determining whether or not the response is ok. This makes it possible to deserialise an `IndexExistsResponse` type with a boolean of whether or not the index exists, even though the response actually contains no data
=> Add index_exists client method

src/elastic/src/client/async.rs, src/elastic/src/client/requests/document_index.rs, src/elastic/src/client/requests/document_put_mapping.rs, src/elastic/src/client/requests/document_update.rs, src/types/benches/mod.rs
For async client methods with a serializable body, we offload the serialisation to a cpu pool if the caller has specified one. The slightly dubious rationale for this is to support offloading as much from the `tokio` thread as possible. This PR just tidies some of that up so we don't duplicate the code for each request that might be async.
=> Add a maybe_async method using serde_pool

src/responses/src/search.rs, src/responses/tests/search/mod.rs
Closes #304 
This shouldn't affect #257 because we're going to store aggregations as `Value`s internally anyways before attempting to interpret them as the various aggregation types.
cc @kardeiz How does this look?
=> Allow getting raw aggregations

src/elastic/src/client/mod.rs, src/elastic/src/client/requests/document_delete.rs, src/elastic/src/client/requests/document_get.rs, src/elastic/src/client/requests/document_index.rs, src/elastic/src/client/requests/document_update.rs, src/types/src/private/impls.rs, tests/run/src/document/compile_test.rs, tests/run/src/document/mod.rs
Fixes #309 
The `DefaultMapping` type being private is causing issues deriving `ElasticType` for structures with fields that use the default mapping, like `HashMap`.
=> Fix up a bug attempting to use default mapping fields

benches/prepare/src/main.rs, src/elastic/examples/basic.rs, src/elastic/examples/basic_async.rs, src/elastic/examples/bulk.rs, src/elastic/examples/bulk_async.rs, src/elastic/examples/custom_response.rs, src/elastic/examples/get.rs, src/elastic/examples/index.rs, src/elastic/examples/load_balanced_async.rs, src/elastic/examples/ping.rs, src/elastic/examples/pre_send.rs, src/elastic/examples/raw.rs, src/elastic/examples/typed.rs, src/elastic/examples/typed_async.rs, src/elastic/examples/update.rs, src/elastic/src/client/requests/document_index.rs, src/elastic/src/lib.rs, src/queries/samples/search/src/main.rs, tests/run/src/document/delete.rs, tests/run/src/document/simple_index_get.rs, tests/run/src/document/update_with_doc.rs, tests/run/src/document/update_with_inline_script.rs, tests/run/src/document/update_with_script.rs, tests/run/src/main.rs, tests/run/src/search/empty_query.rs, tests/run/src/search/raw_query_string.rs
For #308
Make it possible to avoid specifying the id parameter on `document_index` requests. There's a bit of an ergonomic hit for `document_index` if you do want to specify an id, but should be sorted by #301
=> Make the id param optional on document_index

src/elastic/src/client/mod.rs, src/elastic/src/client/sender/async.rs
Fixes #321 
Require a pre-send function to be `Send + Sync` so that the `AsyncClient` is `Send + Sync` again.
=> Ensure async client is send + sync

src/responses/src/search.rs
Closes #323 
Adds the `_id` field to our hits, which was missed previously.
=> Add _id field to search hits

README.md, examples/account_sample/Cargo.toml, src/elastic/Cargo.toml, src/elastic/src/client/requests/bulk/stream.rs, src/elastic/src/client/sender/async.rs, src/elastic/src/lib.rs, src/elastic_derive/Cargo.toml, src/requests/Cargo.toml, src/responses/Cargo.toml, src/responses/src/lib.rs, src/types/Cargo.toml, src/types/src/lib.rs, src/types/tests/derive_compile_test/Cargo.toml, src/types_derive/Cargo.toml, src/types_derive_internals/Cargo.toml, tests/run/Cargo.toml, tests/run/src/bulk/index_get.rs, tests/run/src/bulk/mod.rs, tests/run/src/bulk/stream.rs, tests/run/src/bulk/stream_tiny_size_limit.rs, tests/run/src/bulk/stream_tiny_timeout.rs, tests/run/src/bulk/stream_zero_size_limit.rs, tests/run/src/document/simple_mapping.rs
Fixes up a bug with `bulk().index(doc)` where we'll send invalid JSON.
=> Prepare for 0.21.0-pre.2 release

src/types_derive_internals/src/elastic_type/mod.rs
The code generated for mapping_definitions was causing linting issues when using the ElasticType derive attribute.
=> Add allow(missing_docs) attribute to generated mapping_definitions code

src/elastic/src/client/requests/document_delete.rs, src/elastic/src/client/requests/document_get.rs, src/elastic/src/client/requests/document_index.rs, src/elastic/src/client/requests/document_update.rs, src/elastic/src/types.rs, src/types/src/derive.rs, src/types/src/document/impls.rs, src/types_derive_internals/src/elastic_type/mod.rs
For #337 
You'd expect the `DEFAULT_TYPE` constant to be used everywhere we expect the default type for newer Elasticsearch versions, but that isn't actually the case. This PR just moves the constant so it's used everywhere without renaming it just yet.
cc @mwilliammyers
=> Make DEFAULT_DOC_TYPE used throughout client and generated code

src/responses/src/error.rs
I didn't really know what to name the variant... I was torn between making it something less generic than `Parsing` vs. following the convention of sticking to the elasticsearch exception type name (`parsing_exception`).
=> Add more ApiError enum variants

src/elastic/Cargo.toml, src/elastic/src/error.rs
Closes #336 
Uses [`rustls`](https://github.com/ctz/rustls) instead of OpenSSL, which simplifies portability (and theoretically safety).
Also uses the new `std::error::Error` APIs for #290.
=> Use rustls for TLS

appveyor.yml, examples/account_sample/src/model/account.rs, src/elastic/src/client/requests/document_delete.rs, src/elastic/src/client/requests/document_get.rs, src/elastic/src/client/requests/document_index.rs, src/elastic/src/lib.rs, src/requests/src/genned.rs, src/requests_codegen/src/gen/mod.rs, src/types/src/derive.rs, src/types/src/document/impls.rs, src/types/src/document/mod.rs, src/types/tests/derive_compile_test/src/main.rs, src/types_derive_internals/src/elastic_type/mod.rs
For #343 
This is a breaking change to our unreleased document derive attributes so they're proper expressions instead of function paths. That means:
```rust
#[elastic(id(expr = "ToString::to_string"))]
id: i32,
```
becomes:
```rust
#[elastic(id(expr = "id.to_string()"))]
id: i32,
```
We also now derive `From<#ty> for Cow<str>` where `#ty` is a request parameter like `Index`, `Type`, `Id`. That makes it easier to stitch these various APIs together.
=> Make derive attributes nicer to work with

src/elastic/src/client/requests/bulk/operation.rs, tests/run/src/bulk/mod.rs, tests/run/src/bulk/raw_index_create.rs, tests/run/src/bulk/raw_index_get.rs
Fixes #346 
We did this in #333 for `DocumentType`s, but missed the raw ones.
=> Fix up invalid doc serialization for bulk_raw

src/elastic/src/client/requests/search.rs
Fixes the links for `types-mod` and `document-mod` in the search documentation.
I'm new to Rust so I'm not sure if I fixed it all correctly. In particular I noticed that the same links are also here https://github.com/elastic-rs/elastic/blob/master/src/elastic/src/client/requests/search.rs#L213-L214 but I couldn't find where that documentation shows up.
=> Fixes broken links in search documentation.

src/elastic/src/client/requests/document_delete.rs, src/elastic/src/client/requests/document_get.rs, src/elastic/src/client/requests/document_index.rs, src/elastic/src/client/requests/document_put_mapping.rs, src/elastic/src/client/requests/document_update.rs
The links for the document related methods were pointing to `Client` to `DocumentClient`. I updated the link.
=> Fixes links to DocumentClient methods.

src/elastic/src/client/requests/mod.rs, src/elastic/src/client/requests/sql.rs, src/elastic/src/client/responses/mod.rs, src/requests/src/genned.rs, src/requests_codegen/spec/sql.query.json, src/responses/src/error.rs, src/responses/src/lib.rs, src/responses/src/sql.rs, tests/run/src/main.rs, tests/run/src/run_tests.rs, tests/run/src/sql/invalid_query.rs, tests/run/src/sql/invalid_syntax.rs, tests/run/src/sql/mod.rs, tests/run/src/sql/select_all.rs
I would like to add support for [Elastic SQL queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/xpack-sql.html). 
I haven't done the integration tests yet but was hoping to get some feedback on the approach first.
=> Adds methods to run Elastic sql queries.

src/responses/src/bulk.rs
It's useful for logging. Also, I use the error JSON to determine if the error is temporary or permanent.
=> exposed ES bulk API error as a raw JSON

src/types/src/document/impls.rs, src/types/src/private/impls.rs
Hi,
this adds a mapping for the `std::collections::HashSet` with the same logic as a plain `Vec`
=> Added mapping for HashSet collection

src/responses/src/search.rs
I went ahead with option 1 just to be safe in case Elasticsearch returns different things... but I can change it and update this PR.
Closes #365
=> Expose highlight in `Hit`

src/elastic/src/client/responses/bulk.rs, src/elastic/src/client/responses/document_delete.rs, src/elastic/src/client/responses/document_get.rs, src/elastic/src/client/responses/document_index.rs, src/elastic/src/client/responses/document_update.rs
Add `sequence_number` and `primary_term` fields/methods to all the things.
Questions:
- Should we name it `seq_no` instead of `sequence_number`?
- Should we link to the [optimistic concurrency control](https://www.elastic.co/guide/en/elasticsearch/reference/current/optimistic-concurrency-control.html) docs?
=> Add support for _seq_no & _primary_term in responses

src/elastic/src/client/requests/bulk/operation.rs, src/elastic/src/client/requests/document_update.rs
Fixed two issues with some bulk APIs
* A few functions took `Fn` when they could be taking `FnOnce`.
* Remove unused TId type parameter from BulkRawOperation::update_script_fluent
=> Bulk api fixes

src/elastic/src/types/document/impls.rs, src/elastic_derive/Cargo.toml, src/elastic_derive/src/date_format/mod.rs, src/elastic_derive/src/elastic_type/mod.rs, src/elastic_derive/src/lib.rs
This is *almost* complete (albeit a little hacky), ant it passes all tests except one. 
I am not sure why [this](https://github.com/elastic-rs/elastic/blob/0f90521cf03304f2bfa870a8511d8cfc4f69d18f/tests/derive_compile_test/src/main.rs#L27) test method and [this](https://github.com/elastic-rs/elastic/blob/0f90521cf03304f2bfa870a8511d8cfc4f69d18f/tests/derive_compile_test/src/main.rs#L47) test method are not being used anymore...
=> Update syn, quote & serde_derive_internals dependencies

src/elastic/src/client/mod.rs, src/elastic/src/client/requests/raw.rs, src/elastic/src/client/responses/bulk.rs
fixed some relative links to different docs. i also changed the docs in the `BulkErrorsResponse` section to more explicitly call out the method required to get `BulkErrorsResponse` as the return type from the client
=> fix some doc links

src/elastic/src/client/requests/bulk/mod.rs, src/elastic/src/client/requests/document_delete.rs, src/elastic/src/client/requests/document_get.rs, src/elastic/src/client/requests/document_index.rs, src/elastic/src/client/requests/document_put_mapping.rs, src/elastic/src/client/requests/document_update.rs, src/elastic/src/client/requests/index_close.rs, src/elastic/src/client/requests/index_create.rs, src/elastic/src/client/requests/index_delete.rs, src/elastic/src/client/requests/index_exists.rs, src/elastic/src/client/requests/index_open.rs, src/elastic/src/client/requests/mod.rs, src/elastic/src/client/requests/ping.rs, src/elastic/src/client/requests/search.rs, src/elastic/src/client/requests/sql.rs
Almost every module in client::requests defines their own Pending struct,
wrapping a Boxed future, using copy+pasted code. This patch implements a
templated Pending type in the client::requests module, and uses it in submodules.
The patch also sets up a type alias called Pending in each of the submodules,
to retain backwards compatibility.
This is also laying some groundwork for opening up `Sender` to different implementations, where the `Pending` type may be a generic instead.
=> Refactor into common Pending type

src/elastic/Cargo.toml, src/elastic/src/types/geo/mod.rs, src/elastic/src/types/mod.rs
@KodrAus, you cool with this? 
- Should I put `chrono` behind a (default) feature before merging this?
- Should I separate them into two features - `geo-shape` and `geo-shape` or is that too much?
=> Add (default) geo-types feature

src/elastic_derive/Cargo.toml, src/elastic_derive/src/date_format/parse.rs, src/elastic_derive/src/lib.rs
All `elastic_derive` tests pass, *but*:
No idea what is going on but if you run `cargo test` from the root of the repo you get a linking error but if you run `cargo build` from the root of the repo it works...
If you run `cargo test` from *any* of the workspace member's directories everything works...
I have tried:
- `rustc 1.39.0-nightly (72b2abfd6 2019-08-29)`
- ` rustc 1.37.0 (eae3437df 2019-08-13)` 
each targeting: `x86_64-apple-darwin` and `x86_64-unknown-linux-musl`.
Here is the error message:
```
Compiling elastic_derive v0.21.0-pre.5 (/Users/wm/Developer/elastic/src/elastic_derive)
warning: unused `#[macro_use]` import
--> src/elastic_derive/src/lib.rs:20:1
|
20 | #[macro_use]
| ^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused `#[macro_use]` import …
```
=> Update nom dependency

src/elastic/examples/update_with_source.rs, src/elastic/src/client/requests/document_update.rs, src/elastic/src/client/responses/document_update.rs, tests/integration/src/tests/document/mod.rs, tests/integration/src/tests/document/update_with_source.rs
In order to maintain backwards compatibility by not introducing a new generic parameter on `UpdateResponse`, I had to use `serde_json::Value` as an intermediate value... 
If we are ok with not maintaining backwards compatibility I can update this PR and introduce a new generic parameter, which will result in something like this: `UpdateRequestBuilder<TSender, TBody, TDocument>`.
As a result, as of right now, you use this like:
```rust
#[derive(Deserialize, ElasticType, Debug)]
struct User {
#[elastic(id)]
id: String,
name: String,
}
#[derive(Serialize, ElasticType, Debug)]
struct UpdateUser {
#[elastic(id)]
id: String,
#[serde(skip_serializing_if = "Option::is_none")]
name: Option<String>,
}
```
```rust
let response = client
.document::<UpdateUser>()
.update(1)
.script(r#"ctx._source.name …
```
=> Add support for _source on update requests
